version: '3.4'

services:
  bookify.api:
    image: bookify.api
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    ports:  
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - bookify-db
  
  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      POSTGRES_DB: bookify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"